// 显式图标映射：navigation.ts 用字符串声明图标，这里按名注册。
// 必须逐个具名导入 —— `import * as Icons` 会让整个 lucide-react（约 780 KB）进入首包。
import {
  Activity,
  Award,
  BrainCircuit,
  CalendarDays,
  Calculator,
  ClipboardList,
  Crown,
  FileCheck2,
  FolderKanban,
  Gauge,
  HeartPulse,
  LayoutGrid,
  Leaf,
  Map,
  Route,
  Stethoscope,
  WalletCards,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export const iconRegistry: Record<string, LucideIcon> = {
  Activity,
  Award,
  BrainCircuit,
  CalendarDays,
  Calculator,
  ClipboardList,
  Crown,
  FileCheck2,
  FolderKanban,
  Gauge,
  HeartPulse,
  LayoutGrid,
  Leaf,
  Map,
  Route,
  Stethoscope,
  WalletCards,
  Wind,
  Wrench,
  Zap,
};
