import type { ColumnDef } from "@tanstack/react-table";
import dayjs from "dayjs";
import { AlertTriangle, ArrowRight, BadgeCheck, Check, ChevronRight, ClipboardCheck, Database, Download, Eye, FileArchive, FileCheck2, FileSearch, FileUp, Fingerprint, Gauge, Link2, Pencil, Plus, RefreshCw, SearchCheck, Send, ShieldCheck, Trash2, Upload, UserRoundCheck, XCircle } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { Chart } from "../../components/charts";
import { DataTable } from "../../components/DataTable";
import { Button, Drawer, FormField, InlineLoading, KpiCard, Modal, PageState, Panel, ProgressBar, Segmented, StatusBadge } from "../../components/ui";
import { mrvTraceNodes } from "../../data/carbon-platform";
import { usePlatformStore } from "../../stores/platform";
import type { EvidenceRecord, MvrAnomaly, WorkflowStatus } from "../../types/domain";
import { downloadBlob, downloadEvidencePackage, fileToDataUrl, hashFile } from "../../utils/downloads";

type MrvTab = "凭证台账" | "数据质量" | "异常中心" | "审核与核查" | "审计日志";
const workflowSteps:WorkflowStatus[]=["草稿","已提交","待复核","复核通过","待核查","核查通过","已锁定","已归档"];
const evidenceTypes=["电费账单","天然气账单","蒸汽或热力账单","燃油采购单","车辆台账","制冷剂补充记录","医疗废物转移联单","水费账单","差旅记录","通勤调查表","仪表照片","抄表记录","排放因子来源文件","第三方核查文件","绿电合同","绿证","碳信用凭证"];

function TraceChain() {
  const [selected,setSelected]=useState<typeof mrvTraceNodes[number]|null>(null);
  return <Panel className="trace-panel" title="MRV 全链路溯源" subtitle="Monitoring · Reporting · Verification ｜点击节点查看来源、修订和上下游关系" action={<span className="trace-health"><i/>链路完整率 96.8%</span>}><div className="trace-chain">{mrvTraceNodes.map((node,index)=><div key={node.id}><button className={selected?.id===node.id?"active":""} onClick={()=>setSelected(node)}><span>{index<3?<Database size={17}/>:index<7?<SearchCheck size={17}/>:index<9?<ClipboardCheck size={17}/>:<ShieldCheck size={17}/>}</span><b>{node.name}</b><small>{index<8?"已完成":"待处理"}</small></button>{index<mrvTraceNodes.length-1&&<ArrowRight size={16}/>}</div>)}</div><Drawer open={Boolean(selected)} onClose={()=>setSelected(null)} title={selected?.name??"溯源节点"} subtitle="MRV 节点详情与审计上下文"><div className="detail-kv">{selected&&<><div><span>数据来源</span><b>{selected.source}</b></div><div><span>设备编号</span><b>{selected.device}</b></div><div><span>采集时间</span><b>{selected.time}</b></div><div><span>责任部门</span><b>{selected.department}</b></div><div><span>操作人员</span><b>{selected.operator}</b></div><div><span>原始值</span><b>{selected.raw}</b></div><div><span>修订值</span><b>{selected.revised}</b></div><div><span>修改原因</span><b>{selected.reason}</b></div></>}</div><Panel title="上下游关联关系"><div className="relation-path"><span>{mrvTraceNodes[Math.max(0,mrvTraceNodes.findIndex((n)=>n.id===selected?.id)-1)]?.name}</span><ArrowRight size={14}/><b>{selected?.name}</b><ArrowRight size={14}/><span>{mrvTraceNodes[Math.min(mrvTraceNodes.length-1,mrvTraceNodes.findIndex((n)=>n.id===selected?.id)+1)]?.name}</span></div></Panel><Panel title="电子凭证与操作日志"><div className="drawer-log"><p><FileCheck2 size={14}/>已关联 3 份电子凭证，哈希校验通过</p><p><UserRoundCheck size={14}/>2026-08-04 09:28 · 系统完成节点一致性校验</p><p><Pencil size={14}/>2026-08-03 16:42 · 李核算修订重复采集值</p></div></Panel></Drawer></Panel>;
}

function EvidenceUpload({ open,onClose }: { open:boolean;onClose:()=>void }) {
  const addEvidence=usePlatformStore((state)=>state.addEvidence);
  const pushToast=usePlatformStore((state)=>state.pushToast);
  const fileRef=useRef<HTMLInputElement>(null);
  const [file,setFile]=useState<File|null>(null);
  const [progress,setProgress]=useState(0);
  const [form,setForm]=useState({type:"电费账单",dataSource:"总院外购电力",period:"2026-07",department:"后勤保障部",campus:"总院" as EvidenceRecord["campus"]});
  const [error,setError]=useState("");
  const choose=(next?:File)=>{if(!next)return;const allow=["pdf","jpg","jpeg","png","xlsx","csv","docx"];const ext=next.name.split(".").pop()?.toLowerCase()??"";if(!allow.includes(ext)){setError("仅支持 PDF、JPG、PNG、XLSX、CSV、DOCX 文件");return;}setFile(next);setError("");setProgress(25);window.setTimeout(()=>setProgress(68),250);window.setTimeout(()=>setProgress(100),520);};
  const submit=async()=>{if(!file){setError("请选择需要上传的凭证文件");return;}const hash=await hashFile(file);const dataUrl=file.size<3_000_000?await fileToDataUrl(file):undefined;const ext=file.name.split(".").pop()?.toUpperCase()??"FILE";addEvidence({id:crypto.randomUUID(),code:`MRV-${dayjs().format("YYYY")}-${String(Date.now()).slice(-6)}`,name:file.name,type:form.type,dataSource:form.dataSource,resultRef:`${form.period} ${form.type.includes("电")?"范围二":"待关联"}`,campus:form.campus,period:form.period,format:ext,size:file.size>1048576?`${(file.size/1048576).toFixed(1)} MB`:`${Math.ceil(file.size/1024)} KB`,uploader:"当前用户",uploadedAt:dayjs().format("YYYY-MM-DD HH:mm"),reviewer:"未分配",reviewStatus:"草稿",validUntil:dayjs().add(1,"year").format("YYYY-MM-DD"),hash,integrity:"完整",department:form.department,dataUrl});pushToast("凭证已上传",`${file.name} 已生成编号和 SHA-256 哈希，可在台账中预览。`,"success");onClose();};
  return <Modal open={open} onClose={onClose} title="上传 MRV 凭证" subtitle="文件将计算 SHA-256 哈希并关联到活动数据" footer={<><Button onClick={onClose}>取消</Button><Button variant="primary" onClick={submit}><Upload size={14}/>上传并建档</Button></>}><input ref={fileRef} hidden type="file" accept=".pdf,.jpg,.jpeg,.png,.xlsx,.csv,.docx" onChange={(e)=>choose(e.target.files?.[0])}/><button className={`upload-dropzone ${file?"has-file":""}`} onClick={()=>fileRef.current?.click()}><FileUp size={32}/><b>{file?file.name:"选择或拖入凭证文件"}</b><small>{file?`${(file.size/1024).toFixed(0)} KB · 点击重新选择`:"支持 PDF、JPG、PNG、XLSX、CSV、DOCX"}</small>{progress>0&&<ProgressBar value={progress}/>}</button>{error&&<p className="form-error"><AlertTriangle size={13}/>{error}</p>}<div className="form-grid"><FormField label="凭证类型" required><select value={form.type} onChange={(e)=>setForm({...form,type:e.target.value})}>{evidenceTypes.map((type)=><option key={type}>{type}</option>)}</select></FormField><FormField label="关联数据源" required><select value={form.dataSource} onChange={(e)=>setForm({...form,dataSource:e.target.value})}><option>总院外购电力</option><option>锅炉房天然气</option><option>中央冷站制冷剂补充</option><option>医疗废物转移处置</option><option>员工通勤调查</option></select></FormField><FormField label="账期" required><input type="month" value={form.period} onChange={(e)=>setForm({...form,period:e.target.value})}/></FormField><FormField label="责任部门" required><input value={form.department} onChange={(e)=>setForm({...form,department:e.target.value})}/></FormField><FormField label="院区" required><select value={form.campus} onChange={(e)=>setForm({...form,campus:e.target.value as EvidenceRecord["campus"]})}><option>总院</option><option>东院区</option><option>西院区</option></select></FormField></div></Modal>;
}

function EvidenceLedger() {
  const {evidences,deleteEvidence,updateEvidence,role,pushToast}=usePlatformStore();
  const [uploadOpen,setUploadOpen]=useState(false);
  const [preview,setPreview]=useState<EvidenceRecord|null>(null);
  const [deleteTarget,setDeleteTarget]=useState<EvidenceRecord|null>(null);
  const canReview=role==="管理员"||role==="审核员"||role==="核查员";
  const download=async(evidence:EvidenceRecord)=>{if(evidence.dataUrl){downloadBlob(await (await fetch(evidence.dataUrl)).blob(),evidence.name)}else{downloadBlob(new Blob([`凭证编号：${evidence.code}\r\n凭证名称：${evidence.name}\r\nSHA-256：${evidence.hash}\r\n本地演示凭证元数据`],{type:"text/plain;charset=utf-8"}),`${evidence.name}.txt`)} };
  const columns=useMemo<ColumnDef<EvidenceRecord>[]>(()=>[
    {accessorKey:"code",header:"凭证编号"},{accessorKey:"name",header:"凭证名称",cell:({row})=><div className="table-primary"><b>{row.original.name}</b><small>{row.original.type}</small></div>},{accessorKey:"dataSource",header:"关联数据源"},{accessorKey:"campus",header:"院区"},{accessorKey:"period",header:"账期"},{accessorKey:"format",header:"格式"},{accessorKey:"size",header:"大小"},{accessorKey:"uploader",header:"上传人"},{accessorKey:"uploadedAt",header:"上传时间"},{accessorKey:"reviewStatus",header:"审核状态",cell:({row})=><StatusBadge value={row.original.reviewStatus}/>},{accessorKey:"hash",header:"文件哈希",cell:({row})=><code className="hash-code" title={row.original.hash}>{row.original.hash.length>18?`${row.original.hash.slice(0,8)}…${row.original.hash.slice(-6)}`:row.original.hash}</code>},{accessorKey:"integrity",header:"完整性",cell:({row})=><StatusBadge value={row.original.integrity}/>},{id:"actions",header:"操作",enableSorting:false,cell:({row})=><div className="row-actions"><button title="预览" onClick={()=>setPreview(row.original)}><Eye size={14}/></button><button title="下载" onClick={()=>download(row.original)}><Download size={14}/></button>{canReview&&row.original.reviewStatus==="待审核"&&<button title="审核通过" onClick={()=>{updateEvidence({...row.original,reviewStatus:"审核通过",reviewer:"当前审核人"});pushToast("凭证审核通过",row.original.name,"success");}}><Check size={14}/></button>}<button className="danger" disabled={row.original.reviewStatus!=="草稿"} title="删除草稿" onClick={()=>setDeleteTarget(row.original)}><Trash2 size={14}/></button></div>}
  ],[canReview,pushToast,updateEvidence]);
  return <><DataTable data={evidences} columns={columns} title="MRV 凭证台账" subtitle="支持真实上传、SHA-256 哈希、预览、下载、审核和草稿删除" actions={<Button variant="primary" onClick={()=>setUploadOpen(true)}><Plus size={14}/>上传凭证</Button>}/><EvidenceUpload open={uploadOpen} onClose={()=>setUploadOpen(false)}/><Drawer open={Boolean(preview)} onClose={()=>setPreview(null)} title={preview?.name??"凭证预览"} subtitle={`${preview?.code??""} · ${preview?.format??""}`} width={620} footer={<><Button onClick={()=>setPreview(null)}>关闭</Button>{preview&&<Button variant="primary" onClick={()=>download(preview)}><Download size={14}/>下载原文件</Button>}</>}>
    {preview&&<div className="evidence-preview">{preview.dataUrl&&["JPG","JPEG","PNG"].includes(preview.format)?<img src={preview.dataUrl} alt={preview.name}/>:preview.dataUrl&&preview.format==="PDF"?<iframe title={preview.name} src={preview.dataUrl}/>:<div className="file-preview-placeholder">{preview.format==="XLSX"||preview.format==="CSV"?<><div className="sheet-preview"><span>数据项</span><span>账期</span><span>原始值</span><span>{preview.dataSource}</span><span>{preview.period}</span><span>已解析</span></div><p>表格数据预览 · 前 20 行</p></>:<><FileSearch size={46}/><h3>{preview.name}</h3><p>{preview.format} 文件已完成哈希校验，可下载原文件查看。</p></>}</div>}<div className="detail-kv"><div><span>关联数据源</span><b>{preview.dataSource}</b></div><div><span>责任部门</span><b>{preview.department}</b></div><div><span>上传人 / 时间</span><b>{preview.uploader} · {preview.uploadedAt}</b></div><div><span>SHA-256</span><b className="break-all">{preview.hash}</b></div></div></div>}
  </Drawer><Modal open={Boolean(deleteTarget)} onClose={()=>setDeleteTarget(null)} title="删除未提交凭证" subtitle="只有草稿凭证可以删除" size="sm" footer={<><Button onClick={()=>setDeleteTarget(null)}>取消</Button><Button variant="danger" onClick={()=>{if(deleteTarget){deleteEvidence(deleteTarget.id);pushToast("草稿凭证已删除",deleteTarget.name,"warning");setDeleteTarget(null);}}}>确认删除</Button></>}><p className="confirm-copy">确定删除 <b>{deleteTarget?.name}</b>？该操作会写入审计日志。</p></Modal></>;
}

function QualityManagement() {
  const quality=[{name:"完整性",value:92,issues:3,reason:"医疗废物账单缺失"},{name:"准确性",value:94,issues:2,reason:"制冷剂台账差异"},{name:"一致性",value:89,issues:4,reason:"账单与表计不一致"},{name:"及时性",value:96,issues:1,reason:"差旅记录延迟"},{name:"可追溯性",value:91,issues:3,reason:"通勤估算缺少附件"},{name:"凭证覆盖率",value:88,issues:5,reason:"范围三凭证不足"}];
  const option={radar:{indicator:quality.map((item)=>({name:item.name,max:100})),axisName:{color:"#9fb0c9"},splitArea:{areaStyle:{color:["rgba(47,134,255,.03)","rgba(47,134,255,.09)"]}}},series:[{type:"radar",data:[{value:quality.map((item)=>item.value),name:"质量评分",areaStyle:{opacity:.22}}]}]};
  return <div className="quality-layout"><Panel title="总体数据质量评分" subtitle="六维模型自动扣分与问题定位"><div className="quality-score"><div className="score-ring"><b>91.7</b><small>综合评分</small></div><Chart option={option} height={300}/></div></Panel><Panel title="质量问题与整改建议" subtitle={`共 ${quality.reduce((s,i)=>s+i.issues,0)} 个问题`}><div className="quality-list">{quality.map((item)=><button key={item.name}><span><b>{item.name}</b><small>{item.reason}</small></span><ProgressBar value={item.value} tone={item.value<90?"orange":"green"}/><strong>{item.value}</strong><em>{item.issues} 个问题</em><ChevronRight size={14}/></button>)}</div></Panel></div>;
}

function AnomalyCenter() {
  const {anomalies,updateAnomaly,pushToast}=usePlatformStore();
  const [selected,setSelected]=useState<MvrAnomaly|null>(null);
  const [action,setAction]=useState<"指派"|"忽略"|"整改"|"关闭">("整改");
  const [owner,setOwner]=useState("");
  const [note,setNote]=useState("");
  const submit=()=>{if(!selected)return;if(!note.trim()){pushToast("请填写处理说明","异常处置必须保留原因和整改说明。","warning");return;}const status:MvrAnomaly["status"]=action==="忽略"?"已忽略":action==="关闭"?"已关闭":"整改中";updateAnomaly({...selected,owner:owner||selected.owner,status,note});pushToast("异常状态已更新",`${selected.object} → ${status}`,"success");setSelected(null);setNote("");};
  const columns=useMemo<ColumnDef<MvrAnomaly>[]>(()=>[
    {accessorKey:"type",header:"异常类型"},{accessorKey:"object",header:"异常对象",cell:({row})=><div className="table-primary"><b>{row.original.object}</b><small>{row.original.description}</small></div>},{accessorKey:"severity",header:"等级",cell:({row})=><StatusBadge value={row.original.severity}/>},{accessorKey:"owner",header:"责任人"},{accessorKey:"occurredAt",header:"发生时间"},{accessorKey:"status",header:"处理状态",cell:({row})=><StatusBadge value={row.original.status}/>},{id:"actions",header:"操作",cell:({row})=><div className="row-actions text-actions">{(["指派","忽略","整改","关闭"] as const).map((item)=><button key={item} disabled={row.original.status==="已关闭"} onClick={()=>{setSelected(row.original);setAction(item);setOwner(row.original.owner);}}>{item}</button>)}</div>}
  ],[]);
  return <><DataTable data={anomalies} columns={columns} title="MRV 异常中心" subtitle="覆盖数据缺失、同比环比、单位、重复、凭证、因子和审核超时"/><Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title={`${action}异常`} subtitle={`${selected?.type??""} · ${selected?.object??""}`} footer={<><Button onClick={()=>setSelected(null)}>取消</Button><Button variant="primary" onClick={submit}>保存处理结果</Button></>}><div className="form-grid"><FormField label="处理动作"><select value={action} onChange={(e)=>setAction(e.target.value as typeof action)}><option>指派</option><option>忽略</option><option>整改</option><option>关闭</option></select></FormField><FormField label="负责人"><input value={owner} onChange={(e)=>setOwner(e.target.value)}/></FormField><FormField label="处理说明" required><textarea rows={5} value={note} onChange={(e)=>setNote(e.target.value)} placeholder="填写判断依据、整改措施或忽略原因"/></FormField><FormField label="上传补充凭证"><input type="file" accept=".pdf,.jpg,.png,.xlsx,.csv,.docx"/></FormField></div></Modal></>;
}

function WorkflowPanel() {
  const {workflow,setWorkflow,role,auditLogs,pushToast}=usePlatformStore();
  const [returnOpen,setReturnOpen]=useState(false);
  const [reason,setReason]=useState("");
  const index=workflowSteps.indexOf(workflow);
  const canAdvance=role==="管理员"||role==="审核员"||role==="核查员";
  const advance=()=>{if(!canAdvance){pushToast("无流程权限",`当前角色 ${role} 不能执行审核或核查流转。`,"danger");return;}if(index>=workflowSteps.length-1)return;setWorkflow(workflowSteps[index+1]);pushToast("流程已推进",`${workflow} → ${workflowSteps[index+1]}`,"success");};
  const returnWorkflow=()=>{if(!reason.trim()){pushToast("请填写退回原因","退回时必须填写原因。","warning");return;}setWorkflow(index>1?workflowSteps[index-2]:"草稿",reason);setReturnOpen(false);setReason("");pushToast("批次已退回","退回原因已写入操作日志。","warning");};
  return <div className="workflow-layout"><Panel title="审核与第三方核查流程" subtitle={`当前状态：${workflow}`} action={<><Button disabled={index<=0} onClick={()=>setReturnOpen(true)}><XCircle size={14}/>退回</Button><Button variant="primary" disabled={index>=workflowSteps.length-1} onClick={advance}><Send size={14}/>推进流程</Button></>}><div className="workflow-chain">{workflowSteps.map((step,stepIndex)=><div key={step} className={stepIndex<index?"done":stepIndex===index?"active":""}><span>{stepIndex<index?<Check size={14}/>:stepIndex+1}</span><b>{step}</b>{stepIndex<workflowSteps.length-1&&<ChevronRight size={15}/>}</div>)}</div><div className="verification-actions"><article><SearchCheck size={20}/><b>查看原始记录</b><small>18 条活动数据</small></article><article><CalculatorIcon/><b>查看计算过程</b><small>公式与单位换算</small></article><article><FileCheck2 size={20}/><b>查看排放因子</b><small>10 个有效版本</small></article><article><Fingerprint size={20}/><b>核验电子凭证</b><small>哈希校验 96.8%</small></article></div></Panel><Panel title="最近流程日志" subtitle="所有操作均可追溯"><div className="audit-list compact">{auditLogs.slice(0,8).map((log)=><p key={log.id}><i/><span><b>{log.action}</b><small>{log.detail}</small></span><em>{log.operator}<br/>{log.at}</em></p>)}</div></Panel><Modal open={returnOpen} onClose={()=>setReturnOpen(false)} title="退回当前核查批次" subtitle="退回会改变流程状态并通知责任人" size="sm" footer={<><Button onClick={()=>setReturnOpen(false)}>取消</Button><Button variant="danger" onClick={returnWorkflow}>确认退回</Button></>}><FormField label="退回原因" required><textarea rows={5} value={reason} onChange={(e)=>setReason(e.target.value)} placeholder="请具体说明数据、因子、公式或凭证问题"/></FormField></Modal></div>;
}

function CalculatorIcon(){return <Gauge size={20}/>}

function AuditLogPanel(){const logs=usePlatformStore((state)=>state.auditLogs);return <Panel title="全量审计日志" subtitle={`${logs.length} 条操作记录`}><div className="audit-list">{logs.map((log)=><p key={log.id}><i/><span><b>{log.action}</b><small>{log.detail}</small></span><em>{log.operator}<br/>{log.at}</em></p>)}</div></Panel>}

export function MRVTraceabilityPage() {
  const store=usePlatformStore();
  const [tab,setTab]=useState<MrvTab>("凭证台账");
  const [exportOpen,setExportOpen]=useState(false);
  const [exporting,setExporting]=useState(false);
  const [options,setOptions]=useState({year:"2026",campus:"总院",scope:"全部范围",category:"全部类别",rawData:true,evidence:true,audit:true,anomaly:true,formula:true});
  const coverage=Math.round(store.evidences.filter((e)=>e.integrity==="完整").length/store.evidences.length*100);
  const quality=Math.round((coverage+94+89+96+91+88)/6);
  const exportPackage=async()=>{setExporting(true);await downloadEvidencePackage(options,store.evidences,store.records);setExporting(false);setExportOpen(false);store.pushToast("MRV 证据包已生成","ZIP 文件包含所选原始数据、凭证、审核、整改和核算公式。","success");};
  return <PageState><div className="mrv-page page-stack">
    <section className="mrv-toolbar"><div><StatusBadge value={store.workflow}/><span>批次 {store.calculation.batchId} · {store.filters.hospital}</span></div><div><Button onClick={()=>store.pushToast("链路已刷新","MRV 节点、凭证哈希和异常状态已重新校验。","success")}><RefreshCw size={14}/>重新校验</Button><Button variant="gold" onClick={()=>setExportOpen(true)}><FileArchive size={15}/>导出证据包</Button></div></section>
    <section className="kpi-row eight"><KpiCard label="凭证覆盖率" value={coverage} unit="%" meta="较上月 +3.2%" tone="cyan" icon={<FileCheck2 size={15}/>}/><KpiCard label="自动采集率" value="86.4" unit="%" meta="能源表计与业务接口" tone="blue" icon={<Database size={15}/>}/><KpiCard label="数据质量评分" value={quality} unit="分" meta="六维质量模型" tone="green" icon={<Gauge size={15}/>}/><KpiCard label="可追溯数据" value="94.8" unit="%" meta="上下游关系完整" tone="purple" icon={<Link2 size={15}/>}/><KpiCard label="待审核" value={store.evidences.filter((e)=>e.reviewStatus==="待审核").length} unit="项" meta="最早等待 2 天" tone="orange" icon={<ClipboardCheck size={15}/>}/><KpiCard label="异常凭证" value={store.evidences.filter((e)=>e.integrity!=="完整").length} unit="项" meta="哈希或关联异常" tone="red" icon={<AlertTriangle size={15}/>}/><KpiCard label="已锁定批次" value={store.batchLocked?1:0} unit="个" meta="年度累计 6 个" tone="gold" icon={<ShieldCheck size={15}/>}/><KpiCard label="最近核查" value="07-18" unit="" meta="第三方核查通过" tone="blue" icon={<BadgeCheck size={15}/>}/></section>
    <TraceChain/>
    <section className="mrv-content"><div className="mrv-tabs"><Segmented value={tab} options={["凭证台账","数据质量","异常中心","审核与核查","审计日志"]} onChange={setTab}/></div>{tab==="凭证台账"&&<EvidenceLedger/>}{tab==="数据质量"&&<QualityManagement/>}{tab==="异常中心"&&<AnomalyCenter/>}{tab==="审核与核查"&&<WorkflowPanel/>}{tab==="审计日志"&&<AuditLogPanel/>}</section>
    <Modal open={exportOpen} onClose={()=>!exporting&&setExportOpen(false)} title="导出 MRV 证据包" subtitle="按核算边界生成结构化 ZIP 文件，便于内部审计和第三方核查" footer={<><Button disabled={exporting} onClick={()=>setExportOpen(false)}>取消</Button><Button variant="primary" disabled={exporting} onClick={exportPackage}>{exporting?<InlineLoading label="正在打包"/>:<><Download size={14}/>生成并下载 ZIP</>}</Button></>}><div className="form-grid"><FormField label="年度"><select value={options.year} onChange={(e)=>setOptions({...options,year:e.target.value})}><option>2024</option><option>2025</option><option>2026</option></select></FormField><FormField label="院区"><select value={options.campus} onChange={(e)=>setOptions({...options,campus:e.target.value})}><option>总院</option><option>东院区</option><option>西院区</option></select></FormField><FormField label="排放范围"><select value={options.scope} onChange={(e)=>setOptions({...options,scope:e.target.value})}><option>全部范围</option><option>范围一</option><option>范围二</option><option>范围三</option></select></FormField><FormField label="数据类别"><select value={options.category} onChange={(e)=>setOptions({...options,category:e.target.value})}><option>全部类别</option><option>能源</option><option>逸散排放</option><option>医疗废物</option><option>供应链</option></select></FormField></div><div className="check-list export-checks">{([['rawData','包含原始数据'],['evidence','包含电子凭证'],['audit','包含审核记录'],['anomaly','包含异常整改记录'],['formula','包含核算公式']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={options[key]} onChange={(e)=>setOptions({...options,[key]:e.target.checked})}/>{label}</label>)}</div>{exporting&&<ProgressBar value={78}/>}</Modal>
  </div></PageState>;
}
