import type { ColumnDef } from "@tanstack/react-table";
import dayjs from "dayjs";
import * as XLSX from "xlsx";
import { AlertTriangle, Building2, Calculator, CheckCircle2, ClipboardCheck, Database, Download, FileArchive, FileDown, FileSpreadsheet, FileText, Filter, FolderSearch2, Import, LockKeyhole, Pencil, Plus, RotateCcw, ShieldCheck, Trash2, UnlockKeyhole } from "lucide-react";
import { useMemo, useRef, useState } from "react";
import { Chart } from "../../components/charts";
import { DataTable } from "../../components/DataTable";
import { Button, Drawer, FormField, InlineLoading, KpiCard, Modal, PageState, Panel, ProgressBar, Segmented, StatusBadge, StepProgress } from "../../components/ui";
import { emissionFactors, hospitalBuildings, sourceCategories } from "../../data/carbon-platform";
import { usePlatformStore } from "../../stores/platform";
import type { ActivityRecord } from "../../types/domain";
import { downloadComplianceReport, downloadCsv, downloadEvidencePackage, downloadWorkbook } from "../../utils/downloads";
import { axisBase } from "../../utils/chart-config";

type AccountingTab = "数据源概览" | "能源结构分析" | "扩展排放";
type ReportType = "PDF报告" | "Excel核算明细" | "CSV数据表" | "MRV证据包ZIP";

const sourceIcons: Record<string,string> = { "外购电力":"⚡","天然气":"♨","外购热力／蒸汽":"♨","制冷剂逸散":"❄","麻醉气体":"✦","医疗废物":"♻","用水":"◉","员工通勤":"◆","公务差旅":"✈","外包洗涤":"≈","绿电与绿证":"☘","MRV凭证":"▣" };

function ActivityRecordEditor({ record, open, onClose }: { record:ActivityRecord|null;open:boolean;onClose:()=>void }) {
  const addRecord=usePlatformStore((state)=>state.addRecord);
  const updateRecord=usePlatformStore((state)=>state.updateRecord);
  const locked=usePlatformStore((state)=>state.batchLocked);
  const pushToast=usePlatformStore((state)=>state.pushToast);
  const base:ActivityRecord=record??{id:crypto.randomUUID(),code:`AD-${String(Date.now()).slice(-6)}`,sourceName:"",category:"外购电力",scope:"范围二",campus:"总院",building:"门诊楼",department:"后勤保障部",month:"2026-07",activity:0,unit:"kWh",factorId:"ef-electricity",factorValue:emissionFactors[0].value,factorSource:emissionFactors[0].source,emission:0,status:"已采集",reviewStatus:"草稿",evidenceStatus:"未关联",estimated:false,updatedAt:dayjs().format("YYYY-MM-DD HH:mm")};
  const [form,setForm]=useState<ActivityRecord>(base);
  const [errors,setErrors]=useState<Record<string,string>>({});
  const set=<K extends keyof ActivityRecord>(key:K,value:ActivityRecord[K])=>setForm((current)=>({...current,[key]:value}));
  const save=()=>{
    const nextErrors:Record<string,string>={};
    if(!form.sourceName.trim()) nextErrors.sourceName="请输入数据源名称";
    if(form.activity===null||Number(form.activity)<0) nextErrors.activity="活动数据必须为不小于 0 的数值";
    if(!form.unit.trim()) nextErrors.unit="请输入活动数据单位";
    if(!form.month) nextErrors.month="请选择核算月份";
    setErrors(nextErrors);
    if(Object.keys(nextErrors).length) return;
    const selectedFactor=emissionFactors.find((item)=>item.id===form.factorId)!;
    const next={...form,factorValue:selectedFactor.value,factorSource:selectedFactor.source,estimated:form.status==="估算值"};
    if (record) updateRecord(next); else addRecord(next);
    pushToast(record?"数据已更新":"数据已新增",`${form.sourceName} 已重新计算并写入当前批次。`,"success");onClose();
  };
  return <Drawer open={open} title={record?"编辑活动数据":"新增活动数据"} subtitle="修改活动数据会自动重新计算排放量" onClose={onClose} footer={<><Button onClick={onClose}>取消</Button><Button variant="primary" disabled={locked} onClick={save}>{locked?<><LockKeyhole size={14}/>批次已锁定</>:"保存并重新核算"}</Button></>}>
    <div className="form-grid"><FormField label="数据源名称" required error={errors.sourceName}><input value={form.sourceName} onChange={(e)=>set("sourceName",e.target.value)} placeholder="例如：门诊楼外购电力"/></FormField><FormField label="数据编号" required><input value={form.code} onChange={(e)=>set("code",e.target.value)}/></FormField><FormField label="数据分类" required><select value={form.category} onChange={(e)=>set("category",e.target.value)}>{sourceCategories.filter((item)=>item!=="组织边界"&&item!=="MRV凭证").map((item)=><option key={item}>{item}</option>)}</select></FormField><FormField label="排放范围" required><select value={form.scope} onChange={(e)=>set("scope",e.target.value as ActivityRecord["scope"])}><option>范围一</option><option>范围二</option><option>范围三</option></select></FormField><FormField label="院区" required><select value={form.campus} onChange={(e)=>set("campus",e.target.value as ActivityRecord["campus"])}><option>总院</option><option>东院区</option><option>西院区</option></select></FormField><FormField label="楼宇" required><input value={form.building} onChange={(e)=>set("building",e.target.value)}/></FormField><FormField label="责任科室" required><input value={form.department} onChange={(e)=>set("department",e.target.value)}/></FormField><FormField label="核算月份" required error={errors.month}><input type="month" value={form.month} onChange={(e)=>set("month",e.target.value)}/></FormField><FormField label="活动数据" required error={errors.activity}><input type="number" min="0" value={form.activity??""} onChange={(e)=>set("activity",e.target.value===""?null:Number(e.target.value))}/></FormField><FormField label="单位" required error={errors.unit}><input value={form.unit} onChange={(e)=>set("unit",e.target.value)} placeholder="kWh / m³ / kg"/></FormField><FormField label="排放因子" required hint="因子来源、版本和有效期可在因子配置中查看"><select value={form.factorId} onChange={(e)=>set("factorId",e.target.value)}>{emissionFactors.map((factor)=><option value={factor.id} key={factor.id}>{factor.name}（{factor.value}）</option>)}</select></FormField><FormField label="数据状态" required><select value={form.status} onChange={(e)=>set("status",e.target.value as ActivityRecord["status"])}><option>已采集</option><option>异常</option><option>估算值</option><option>缺失</option></select></FormField></div>
  </Drawer>;
}

function CarbonSpatial({ open,onClose }: { open:boolean;onClose:()=>void }) {
  const [selected,setSelected]=useState(hospitalBuildings[0]);
  return <Modal open={open} onClose={onClose} title="医院碳空间剖析" subtitle="2D 等轴测院区 · 点击建筑查看能源与碳排放画像" size="xl" footer={<Button onClick={onClose}>返回核算工作台</Button>}>
    <div className="spatial-layout"><div className="spatial-map"><img src="/dashboard/hospital-night-campus.webp" alt="医院院区数字孪生底图"/>{hospitalBuildings.map((building)=><button key={building.name} style={{left:`${building.left}%`,top:`${building.top}%`}} className={selected.name===building.name?"active":""} onClick={()=>setSelected(building)}><i/><span>{building.name}</span><small>{building.emission} tCO₂e</small></button>)}</div><aside><h3>{selected.name}</h3><StatusBadge value={selected.alarm}/><dl><div><dt>用电量</dt><dd>{selected.electricity.toLocaleString()} kWh</dd></div><div><dt>天然气</dt><dd>{selected.gas.toLocaleString()} m³</dd></div><div><dt>碳排放量</dt><dd>{selected.emission} tCO₂e</dd></div><div><dt>单位面积排放</dt><dd>{selected.areaEmission} kgCO₂e/㎡</dd></div><div><dt>单位床日排放</dt><dd>{selected.bedDay||"—"} {selected.bedDay?"kgCO₂e/床日":""}</dd></div></dl><div className="mini-trend"><span>近 7 日排放趋势</span><div>{[38,56,48,62,74,58,66].map((value,index)=><i key={index} style={{height:`${value}%`}}/>)}</div></div></aside></div>
  </Modal>;
}

function DataSourceOverview({ records,category,setCategory,onEdit,onDelete }: { records:ActivityRecord[];category:string;setCategory:(value:string)=>void;onEdit:(record:ActivityRecord|null)=>void;onDelete:(record:ActivityRecord)=>void }) {
  const storeRecords=usePlatformStore((state)=>state.records);
  const locked=usePlatformStore((state)=>state.batchLocked);
  const pushToast=usePlatformStore((state)=>state.pushToast);
  const [selected,setSelected]=useState<ActivityRecord[]>([]);
  const [reviewOpen,setReviewOpen]=useState(false);
  const [reviewNote,setReviewNote]=useState("");
  const reviewRecords=usePlatformStore((state)=>state.reviewRecords);
  const fileRef=useRef<HTMLInputElement>(null);
  const [importState,setImportState]=useState<{open:boolean;name:string;progress:number;success:number;failed:number;duplicates:number}>({open:false,name:"",progress:0,success:0,failed:0,duplicates:0});
  const addRecord=usePlatformStore((state)=>state.addRecord);
  const stats=sourceCategories.map((name)=>{const matches=name==="组织边界"?storeRecords.filter((r)=>r.building):name==="MRV凭证"?storeRecords.filter((r)=>r.evidenceStatus!=="未关联"):storeRecords.filter((r)=>r.category===name);const expected=Math.max(matches.length,name==="外购电力"?3:name==="医疗废物"?2:1);return {name,collected:matches.filter((r)=>r.status!=="缺失").length,expected,missing:matches.filter((r)=>r.status==="缺失").length,abnormal:matches.filter((r)=>r.status==="异常").length};});
  const doReview=(decision:"通过"|"退回修改")=>{if(!selected.length){pushToast("未选择数据","请先勾选需要复核的活动数据。","warning");return;}if(!reviewNote.trim()){pushToast("请填写复核意见","审核记录必须包含可追溯的复核意见。","warning");return;}reviewRecords(selected.map((item)=>item.id),decision,reviewNote);setReviewOpen(false);setReviewNote("");pushToast(decision==="通过"?"复核完成":"已退回修改",`${selected.length} 条数据状态已更新并写入操作日志。`,decision==="通过"?"success":"warning");};
  const importFile=async(file?:File)=>{if(!file)return;setImportState({open:true,name:file.name,progress:15,success:0,failed:0,duplicates:0});try{const bytes=await file.arrayBuffer();setImportState((s)=>({...s,progress:48}));const workbook=XLSX.read(bytes);const rows=XLSX.utils.sheet_to_json<Record<string,unknown>>(workbook.Sheets[workbook.SheetNames[0]],{defval:""});let success=0,failed=0,duplicates=0;for(const [index,row] of rows.entries()){const name=String(row["数据源名称"]||row["sourceName"]||"");const activity=Number(row["活动数据"]||row["activity"]);if(!name||Number.isNaN(activity)){failed++;continue;}if(storeRecords.some((item)=>item.sourceName===name&&item.month===String(row["核算月份"]||"2026-07"))){duplicates++;continue;}addRecord({id:crypto.randomUUID(),code:String(row["编号"]||`IMP-${Date.now()}-${index}`),sourceName:name,category:String(row["分类"]||"外购电力"),scope:(String(row["排放范围"]||"范围二") as ActivityRecord["scope"]),campus:(String(row["院区"]||"总院") as ActivityRecord["campus"]),building:String(row["楼宇"]||"门诊楼"),department:String(row["科室"]||"后勤保障部"),month:String(row["核算月份"]||"2026-07"),activity,unit:String(row["单位"]||"kWh"),factorId:"ef-electricity",factorValue:emissionFactors[0].value,factorSource:emissionFactors[0].source,emission:0,status:"已采集",reviewStatus:"草稿",evidenceStatus:"未关联",estimated:false,updatedAt:dayjs().format("YYYY-MM-DD HH:mm")});success++;}setImportState((s)=>({...s,progress:100,success,failed,duplicates}));}catch{setImportState((s)=>({...s,progress:100,failed:1}));}};
  const columns=useMemo<ColumnDef<ActivityRecord>[]>(()=>[
    {accessorKey:"code",header:"编号"},{accessorKey:"sourceName",header:"数据源名称",cell:({row})=><div className="table-primary"><b>{row.original.sourceName}</b><small>{row.original.department}</small></div>},{accessorKey:"category",header:"分类"},{accessorKey:"scope",header:"范围"},{accessorKey:"campus",header:"院区"},{accessorKey:"building",header:"楼宇"},{accessorKey:"month",header:"账期"},{accessorKey:"activity",header:"活动数据",cell:({row})=>row.original.activity===null?<span className="missing-value">暂无数据</span>:<b>{row.original.activity.toLocaleString()} <small>{row.original.unit}</small></b>},{accessorKey:"factorValue",header:"排放因子",cell:({row})=><span title={`${row.original.factorSource}`}>{row.original.factorValue}</span>},{accessorKey:"emission",header:"排放量",cell:({row})=>row.original.emission===null?"—":`${row.original.emission.toLocaleString()} t`},{accessorKey:"status",header:"数据状态",cell:({row})=><StatusBadge value={row.original.status}/>},{accessorKey:"reviewStatus",header:"审核",cell:({row})=><StatusBadge value={row.original.reviewStatus}/>},{accessorKey:"evidenceStatus",header:"凭证",cell:({row})=><StatusBadge value={row.original.evidenceStatus}/>},{id:"actions",header:"操作",enableSorting:false,cell:({row})=><div className="row-actions"><button disabled={locked} title="编辑" onClick={()=>onEdit(row.original)}><Pencil size={14}/></button><button title="导出当前行" onClick={()=>downloadCsv([row.original as unknown as Record<string,unknown>],`${row.original.code}.csv`)}><FileDown size={14}/></button><button disabled={locked} className="danger" title="删除" onClick={()=>onDelete(row.original)}><Trash2 size={14}/></button></div>}
  ],[locked,onDelete,onEdit]);
  return <>
    <div className="source-cards">{stats.map((item)=>{const rate=Math.round(item.collected/item.expected*100);return <button key={item.name} className={category===item.name?"active":""} onClick={()=>setCategory(category===item.name?"全部":item.name)}><span className="source-card-icon">{sourceIcons[item.name]??"◇"}</span><span><b>{item.name}</b><small>{item.collected}/{item.expected} 已采集</small></span><strong className={rate<80?"warn":""}>{rate}%</strong><ProgressBar value={rate} tone={rate<80?"orange":"green"}/><footer><i>{item.missing} 缺失</i><em>{item.abnormal} 异常</em></footer></button>})}</div>
    <div className="record-filters"><label><Filter size={14}/><select value={category} onChange={(e)=>setCategory(e.target.value)}><option>全部</option>{sourceCategories.map((item)=><option key={item}>{item}</option>)}</select></label><span>分类卡片与明细表已联动</span></div>
    <DataTable data={records} columns={columns} title="数据源明细表" subtitle={`当前 ${records.length} 条 · ${locked?"批次已锁定，仅可查看":"支持新增、导入、复核和审计追踪"}`} selectable onSelectionChange={setSelected} actions={<><input ref={fileRef} hidden type="file" accept=".csv,.xlsx,.xls" onChange={(e)=>importFile(e.target.files?.[0])}/><Button disabled={locked} onClick={()=>fileRef.current?.click()}><Import size={14}/>批量导入</Button><Button disabled={locked} onClick={()=>onEdit(null)}><Plus size={14}/>新增</Button><Button disabled={!selected.length} onClick={()=>setReviewOpen(true)}><ClipboardCheck size={14}/>批量复核</Button><Button onClick={()=>downloadWorkbook({核算明细:records as unknown as Record<string,unknown>[]},"医院碳核算明细.xlsx")}><Download size={14}/>导出</Button></>}/>
    <Modal open={reviewOpen} onClose={()=>setReviewOpen(false)} title="批量复核活动数据" subtitle={`已选择 ${selected.length} 条数据，复核操作将写入审计日志`} footer={<><Button onClick={()=>setReviewOpen(false)}>取消</Button><Button variant="danger" onClick={()=>doReview("退回修改")}>退回修改</Button><Button variant="primary" onClick={()=>doReview("通过")}>通过复核</Button></>}><FormField label="复核意见" required><textarea rows={5} value={reviewNote} onChange={(e)=>setReviewNote(e.target.value)} placeholder="填写数据完整性、凭证一致性和异常处置意见"/></FormField></Modal>
    <Modal open={importState.open} onClose={()=>setImportState((s)=>({...s,open:false}))} title="活动数据批量导入" subtitle={importState.name} footer={<><Button onClick={()=>setImportState((s)=>({...s,open:false}))}>关闭</Button>{importState.failed>0&&<Button onClick={()=>downloadCsv([{行号:2,错误:"数据源名称或活动数据为空"}],"导入错误清单.csv")}>下载错误清单</Button>}</>}><div className="import-progress"><FileSpreadsheet size={34}/><ProgressBar value={importState.progress}/><b>{importState.progress<100?`正在解析 ${importState.progress}%`:"解析完成"}</b><div><span>成功 <b>{importState.success}</b></span><span>失败 <b>{importState.failed}</b></span><span>重复 <b>{importState.duplicates}</b></span></div></div></Modal>
  </>;
}

function EnergyAnalysis({ onToast }: { onToast:(title:string,message:string)=>void }) {
  const sankey={tooltip:{trigger:"item"},series:[{type:"sankey",left:18,right:18,top:28,bottom:22,nodeWidth:16,nodeGap:14,draggable:true,emphasis:{focus:"adjacency"},lineStyle:{color:"gradient",curveness:.48,opacity:.42},label:{color:"#c8d6ea",fontSize:11},data:[{name:"外购电力",itemStyle:{color:"#2f86ff"}},{name:"天然气",itemStyle:{color:"#ff9f43"}},{name:"绿电",itemStyle:{color:"#31d58b"}},{name:"配电系统"},{name:"锅炉系统"},{name:"中央冷站"},{name:"门诊楼"},{name:"住院楼"},{name:"医技楼"},{name:"行政楼"},{name:"照明"},{name:"空调"},{name:"医疗设备"},{name:"热水"},{name:"碳排放",itemStyle:{color:"#ff6b6b"}}],links:[{source:"外购电力",target:"配电系统",value:68},{source:"绿电",target:"配电系统",value:12},{source:"天然气",target:"锅炉系统",value:22},{source:"配电系统",target:"中央冷站",value:25},{source:"配电系统",target:"门诊楼",value:18},{source:"配电系统",target:"住院楼",value:20},{source:"配电系统",target:"医技楼",value:17},{source:"锅炉系统",target:"住院楼",value:14},{source:"锅炉系统",target:"热水",value:8},{source:"中央冷站",target:"空调",value:25},{source:"门诊楼",target:"照明",value:6},{source:"门诊楼",target:"医疗设备",value:12},{source:"住院楼",target:"照明",value:7},{source:"住院楼",target:"医疗设备",value:13},{source:"医技楼",target:"医疗设备",value:17},{source:"照明",target:"碳排放",value:13},{source:"空调",target:"碳排放",value:25},{source:"医疗设备",target:"碳排放",value:42},{source:"热水",target:"碳排放",value:8}]}]};
  const rankOption={tooltip:{trigger:"axis"},grid:{left:78,right:18,top:20,bottom:25},xAxis:{type:"value",...axisBase()},yAxis:{type:"category",data:["行政楼","门诊楼","住院楼","医技楼","锅炉房"],...axisBase()},series:[{type:"bar",data:[226,842,1290,1486,1692],barWidth:13,itemStyle:{color:"#2f86ff",borderRadius:[0,6,6,0]}}]};
  const trendOption={tooltip:{trigger:"axis"},legend:{data:["排放量","单位床日"],textStyle:{color:"#9fb0c9"}},grid:{left:42,right:42,top:38,bottom:28},xAxis:{type:"category",data:["1月","2月","3月","4月","5月","6月","7月"],...axisBase()},yAxis:[{type:"value",...axisBase()},{type:"value",...axisBase()}],series:[{name:"排放量",type:"line",smooth:true,data:[2860,2690,2480,2290,2180,2060,1988],areaStyle:{opacity:.12}},{name:"单位床日",type:"line",yAxisIndex:1,smooth:true,data:[52,51,49,48,47,46.8,46.2]}]};
  return <div className="analysis-grid"><Panel className="sankey-panel" title="医院能源流向桑基图" subtitle="能源输入 → 供能系统 → 医院楼宇 → 终端场景 → 碳排放" action={<Segmented value="月度" options={["月度","年度"]} onChange={()=>{}}/>}><Chart height={390} option={sankey} onEvents={{click:(params)=>{const p=params as {name?:string};onToast("图表联动",`已定位 ${p.name??"能源流向"}，相关上下游节点已高亮。`);}}}/></Panel><Panel title="各楼宇排放排名" subtitle="tCO₂e"><Chart height={280} option={rankOption}/></Panel><Panel className="wide-panel" title="月度排放与强度趋势" subtitle="支持 Tooltip、图例开关和双轴对比"><Chart height={300} option={trendOption}/></Panel><div className="intensity-cards"><KpiCard label="单位建筑面积" value="38.6" unit="kgCO₂e/㎡" meta="同比 -4.2%" tone="cyan"/><KpiCard label="单位床日" value="46.2" unit="kgCO₂e/床日" meta="同比 -3.8%" tone="green"/><KpiCard label="单位门诊人次" value="2.84" unit="kgCO₂e/人次" meta="同比 -2.1%" tone="purple"/></div></div>;
}

function ScopeThree() {
  const categories=["医疗废物","一般废物","员工通勤","公务差旅","用水及污水","外包洗涤","医疗物资采购","药品和耗材采购","餐饮供应链"];
  const [statuses,setStatuses]=useState<Record<string,string>>(()=>JSON.parse(localStorage.getItem("hsc-scope3-status")||"{}"));
  const update=(name:string,value:string)=>{const next={...statuses,[name]:value};setStatuses(next);localStorage.setItem("hsc-scope3-status",JSON.stringify(next));};
  return <div className="scope-three-grid">{categories.map((name,index)=>{const value=statuses[name]??(index===2||index===6?"使用估算值":index===8?"缺少数据":"纳入核算");return <article key={name}><header><span>{sourceIcons[name]??"◇"}</span><div><b>{name}</b><small>范围三 · 上游/下游间接排放</small></div><StatusBadge value={value}/></header><div className="scope-three-metric"><strong>{[55.6,28.4,182.6,12.2,18.4,156.6,326.8,418.2,64.5][index]} <small>tCO₂e</small></strong><span>凭证覆盖率 {Math.max(42,96-index*5)}%</span></div><label>核算策略<select value={value} onChange={(e)=>update(name,e.target.value)}><option>纳入核算</option><option>暂不纳入</option><option>缺少数据</option><option>使用估算值</option></select></label>{value==="使用估算值"&&<p><AlertTriangle size={13}/>估算值：采用行业基准模型，不与实测数据混淆</p>}</article>})}</div>;
}

export function CarbonAccountingPage() {
  const store=usePlatformStore();
  const [tab,setTab]=useState<AccountingTab>("数据源概览");
  const [standard,setStandard]=useState("组织温室气体排放核算");
  const [month,setMonth]=useState("2026-07");
  const [org,setOrg]=useState("全院运营控制边界");
  const [category,setCategory]=useState("全部");
  const [editor,setEditor]=useState<{open:boolean;record:ActivityRecord|null}>({open:false,record:null});
  const [deleteTarget,setDeleteTarget]=useState<ActivityRecord|null>(null);
  const [calc,setCalc]=useState({open:false,step:0,done:false});
  const [lockModal,setLockModal]=useState(false);
  const [unlockReason,setUnlockReason]=useState("");
  const [reportOpen,setReportOpen]=useState(false);
  const [reportType,setReportType]=useState<ReportType>("PDF报告");
  const [reportOptions,setReportOptions]=useState({scope3:true,anomalies:true});
  const [reporting,setReporting]=useState(false);
  const [spatialOpen,setSpatialOpen]=useState(false);
  const visibleRecords=store.records.filter((record)=>(store.filters.hospital==="总院"?true:record.campus===store.filters.hospital)&&(category==="全部"||category==="组织边界"||category==="MRV凭证"||record.category===category)&&record.month.startsWith(String(store.filters.year))&&(month?record.month===month:true));
  const metrics={total:store.records.length,collected:store.records.filter((r)=>r.status!=="缺失").length,missing:store.records.filter((r)=>r.status==="缺失").length,abnormal:store.records.filter((r)=>r.status==="异常").length,evidence:Math.round(store.records.filter((r)=>r.evidenceStatus==="审核通过").length/store.records.length*100)};
  const startCalculation=()=>{setCalc({open:true,step:0,done:false});[1,2,3,4].forEach((step)=>window.setTimeout(()=>setCalc((current)=>({...current,step})),step*430));window.setTimeout(()=>{const result=store.calculate();setCalc({open:true,step:5,done:true});store.pushToast(result.missingIds.length?"试算完成，存在缺失项":"试算完成",`排放总量 ${result.total.toLocaleString()} tCO₂e，质量评分 ${result.qualityScore}。`,result.missingIds.length?"warning":"success");},2250);};
  const generateReport=async()=>{setReporting(true);await new Promise((resolve)=>setTimeout(resolve,900));if(reportType==="PDF报告")downloadComplianceReport(store.calculation,store.records,reportOptions.scope3,reportOptions.anomalies);if(reportType==="Excel核算明细")downloadWorkbook({核算结果:[{批次:store.calculation.batchId,总排放:store.calculation.total,范围一:store.calculation.scope1,范围二:store.calculation.scope2,范围三:store.calculation.scope3,质量分:store.calculation.qualityScore}],活动数据:store.records as unknown as Record<string,unknown>[]},"医院碳核算合规报告.xlsx");if(reportType==="CSV数据表")downloadCsv(store.records as unknown as Record<string,unknown>[],"医院碳核算明细.csv");if(reportType==="MRV证据包ZIP")await downloadEvidencePackage({rawData:true,evidence:true,audit:true,anomaly:reportOptions.anomalies,formula:true},store.evidences,store.records);setReporting(false);setReportOpen(false);store.pushToast("文件已生成",`${reportType} 已开始下载，可在浏览器下载记录中查看。`,"success");};
  const confirmLock=()=>{if(store.batchLocked){if(store.role!=="管理员"){store.pushToast("无解锁权限","只有管理员可以解锁正式核算批次。","danger");return;}setLockModal(true);return;}setLockModal(true);};
  const toggleLock=()=>{if(store.batchLocked&&!unlockReason.trim()){store.pushToast("请输入解锁原因","解锁原因将写入审计日志。","warning");return;}store.setBatchLocked(!store.batchLocked,store.batchLocked?unlockReason:"完成核算复核，进入不可编辑状态");setLockModal(false);setUnlockReason("");store.pushToast(store.batchLocked?"批次已解锁":"批次已锁定",store.batchLocked?"活动数据恢复可编辑状态。":"当前批次已禁止编辑，锁定记录已写入审计日志。","success");};
  return <PageState onReset={store.restoreDemo}><div className="accounting-page page-stack">
    <section className="accounting-toolbar"><div className="toolbar-title"><Calculator size={21}/><div><h2>医院温室气体核算</h2><p>当前批次 {store.calculation.batchId} · {store.batchLocked?"已锁定":"可编辑"}</p></div><StatusBadge value={store.batchLocked?"已锁定":"核算中"}/></div><label>核算标准<select value={standard} onChange={(e)=>setStandard(e.target.value)}><option>组织温室气体排放核算</option><option>ISO 14064-1</option><option>GHG Protocol</option><option>医院自定义核算指南</option></select></label><label>核算年月<input type="month" value={month} onChange={(e)=>setMonth(e.target.value)}/></label><label>组织范围<select value={org} onChange={(e)=>setOrg(e.target.value)}><option>全院运营控制边界</option><option>总院</option><option>东院区</option><option>西院区</option></select></label><Button onClick={()=>{if(confirm("确定恢复初始演示数据？当前未导出的编辑将被覆盖。")){store.restoreDemo();store.pushToast("演示数据已恢复","核算、资产和 MRV 数据已恢复到初始状态。","success");}}}><RotateCcw size={14}/>恢复数据</Button><Button variant="gold" onClick={()=>setSpatialOpen(true)}><Building2 size={15}/>医院碳空间剖析</Button></section>
    <section className="accounting-actions"><Button variant="primary" onClick={startCalculation}><Calculator size={15}/>一键试算</Button><Button disabled={store.batchLocked} onClick={()=>{setTab("数据源概览");store.pushToast("批量复核","请在下方明细表勾选数据后发起复核。","info");}}><ClipboardCheck size={15}/>批量复核</Button><Button onClick={confirmLock}>{store.batchLocked?<UnlockKeyhole size={15}/>:<LockKeyhole size={15}/>} {store.batchLocked?"解锁批次":"锁定批次"}</Button><Button variant="gold" onClick={()=>setReportOpen(true)}><FileText size={15}/>生成合规报告</Button><div className="standard-note"><ShieldCheck size={15}/><span>当前标准：{standard}<small>因子、版本与核算规则均可配置 · 估算值单独标记</small></span></div></section>
    <div className="accounting-tabs"><Segmented value={tab} options={["数据源概览","能源结构分析","扩展排放"]} onChange={setTab}/></div>
    <section className="kpi-row five"><KpiCard label="数据源总数" value={metrics.total} unit="项" meta="覆盖 20 类医院活动数据" icon={<Database size={15}/>} tone="cyan"/><KpiCard label="已采集数" value={metrics.collected} unit="项" meta={`${Math.round(metrics.collected/metrics.total*100)}% 已就绪`} icon={<CheckCircle2 size={15}/>} tone="green"/><KpiCard label="缺失数" value={metrics.missing} unit="项" meta="试算后可前往补录" icon={<AlertTriangle size={15}/>} tone="red"/><KpiCard label="异常数" value={metrics.abnormal} unit="项" meta="需复核数据与账单" icon={<AlertTriangle size={15}/>} tone="orange"/><KpiCard label="凭证覆盖率" value={metrics.evidence} unit="%" meta={`质量评分 ${store.calculation.qualityScore}`} icon={<FolderSearch2 size={15}/>} tone="blue"/></section>
    {tab==="数据源概览"&&<DataSourceOverview records={visibleRecords} category={category} setCategory={setCategory} onEdit={(record)=>setEditor({open:true,record})} onDelete={setDeleteTarget}/>} {tab==="能源结构分析"&&<EnergyAnalysis onToast={(title,message)=>store.pushToast(title,message,"info")}/>} {tab==="扩展排放"&&<ScopeThree/>}
    <ActivityRecordEditor key={editor.record?.id??"new"} open={editor.open} record={editor.record} onClose={()=>setEditor({open:false,record:null})}/>
    <Modal open={Boolean(deleteTarget)} onClose={()=>setDeleteTarget(null)} title="删除活动数据" subtitle="删除后将影响当前批次排放结果，操作会写入审计日志" size="sm" footer={<><Button onClick={()=>setDeleteTarget(null)}>取消</Button><Button variant="danger" onClick={()=>{if(deleteTarget){store.deleteRecord(deleteTarget.id);store.pushToast("数据已删除",`${deleteTarget.sourceName} 已从当前批次移除。`,"warning");setDeleteTarget(null);}}}>确认删除</Button></>}><p className="confirm-copy">确定删除 <b>{deleteTarget?.sourceName}</b>？请在删除后重新执行试算。</p></Modal>
    <Modal open={calc.open} onClose={()=>calc.done&&setCalc((s)=>({...s,open:false}))} title="医院碳排放一键试算" subtitle="依次校验活动数据、因子版本和 MRV 凭证" footer={calc.done?<><Button onClick={()=>setCalc((s)=>({...s,open:false}))}>关闭</Button>{store.calculation.missingIds.length>0&&<Button variant="primary" onClick={()=>{setCalc((s)=>({...s,open:false}));setTab("数据源概览");setCategory("医疗废物");document.querySelector(".data-table-card")?.scrollIntoView({behavior:"smooth"});}}>前往补录</Button>}</>:undefined}><StepProgress steps={["完整性校验","范围一","范围二","范围三","结果汇总"]} current={calc.step}/><div className="calculation-progress">{calc.done?<><CheckCircle2/><h3>试算完成</h3><strong>{store.calculation.total.toLocaleString()} <small>tCO₂e</small></strong><p>范围一 {store.calculation.scope1} · 范围二 {store.calculation.scope2} · 范围三 {store.calculation.scope3}</p>{store.calculation.missingIds.length>0&&<div className="warning-box"><AlertTriangle size={16}/>发现 {store.calculation.missingIds.length} 项缺失数据，结果已标记为待复核。</div>}</>:<><InlineLoading label="正在执行核算与质量校验"/><ProgressBar value={calc.step*20+8}/><p>排放因子版本、单位换算和估算值标识正在校验…</p></>}</div></Modal>
    <Modal open={lockModal} onClose={()=>setLockModal(false)} title={store.batchLocked?"解锁核算批次":"锁定核算批次"} subtitle={store.batchLocked?"仅管理员可解锁，原因将进入审计日志":"锁定后本批次活动数据不可编辑"} size="sm" footer={<><Button onClick={()=>setLockModal(false)}>取消</Button><Button variant={store.batchLocked?"danger":"primary"} onClick={toggleLock}>{store.batchLocked?"确认解锁":"确认锁定"}</Button></>}>{store.batchLocked?<FormField label="解锁原因" required><textarea rows={4} value={unlockReason} onChange={(e)=>setUnlockReason(e.target.value)} placeholder="例如：第三方核查发现需补充账单数据"/></FormField>:<div className="warning-box"><LockKeyhole size={16}/>锁定后仍可查看、导出和生成报告，但新增、编辑、删除和复核入口会被禁用。</div>}</Modal>
    <Modal open={reportOpen} onClose={()=>!reporting&&setReportOpen(false)} title="生成合规报告" subtitle="选择交付格式和报告内容，文件由浏览器本地生成" footer={<><Button disabled={reporting} onClick={()=>setReportOpen(false)}>取消</Button><Button variant="primary" disabled={reporting} onClick={generateReport}>{reporting?<InlineLoading label="正在生成"/>:<><Download size={14}/>生成并下载</>}</Button></>}><div className="report-types">{(["PDF报告","Excel核算明细","CSV数据表","MRV证据包ZIP"] as ReportType[]).map((type)=>{const Icon=type.includes("PDF")?FileText:type.includes("Excel")?FileSpreadsheet:type.includes("ZIP")?FileArchive:FileDown;return <button key={type} className={reportType===type?"active":""} onClick={()=>setReportType(type)}><Icon size={22}/><b>{type}</b><small>{type==="MRV证据包ZIP"?"含数据、凭证和公式":"按当前筛选范围生成"}</small></button>})}</div><div className="check-list"><label><input type="checkbox" checked={reportOptions.scope3} onChange={(e)=>setReportOptions((s)=>({...s,scope3:e.target.checked}))}/>报告包含范围三</label><label><input type="checkbox" checked={reportOptions.anomalies} onChange={(e)=>setReportOptions((s)=>({...s,anomalies:e.target.checked}))}/>报告包含异常说明</label></div>{reporting&&<ProgressBar value={82}/>}</Modal>
    <CarbonSpatial open={spatialOpen} onClose={()=>setSpatialOpen(false)}/>
  </div></PageState>;
}
