import type { ColumnDef } from "@tanstack/react-table";
import dayjs from "dayjs";
import { Check, ChevronRight, Download, FileCheck2, FilePenLine, Leaf, MoreHorizontal, Pencil, Plus, Settings2, ShoppingCart, SlidersHorizontal, Target, Trash2, TrendingDown, Zap } from "lucide-react";
import { useState } from "react";
import { Chart } from "../../components/charts";
import { DataTable } from "../../components/DataTable";
import { Button, FormField, Modal, PageState, Panel, ProgressBar, Segmented, StatusBadge } from "../../components/ui";
import { monthlyEmission } from "../../data/carbon-platform";
import { usePlatformStore } from "../../stores/platform";
import type { AnnualTask, AssetTransaction, StrategyPlan } from "../../types/domain";
import { downloadWorkbook } from "../../utils/downloads";
import { axisBase } from "../../utils/chart-config";

type AssetTab = "月度排放与预算" | "交易记录" | "碳资产增值" | "合规雷达" | "核查准备" | "减排项目";
type StrategyName = "直接购买碳信用" | "购买CCER抵消" | "购买绿电" | "购买绿证" | "实施节能项目" | "优化能源调度" | "调整内部碳预算";

const strategies:{name:StrategyName;icon:typeof Leaf;desc:string;tone:string;price:number;reduction:number}[]=[
  {name:"直接购买碳信用",icon:ShoppingCart,desc:"交付快，价格受市场波动影响",tone:"blue",price:96,reduction:1},{name:"购买CCER抵消",icon:Leaf,desc:"优先选用高质量减排项目",tone:"green",price:82,reduction:1},{name:"购买绿电",icon:Zap,desc:"降低范围二市场法排放",tone:"cyan",price:0.08,reduction:.00057},{name:"购买绿证",icon:FileCheck2,desc:"补充可再生能源消费凭证",tone:"gold",price:46,reduction:.001},{name:"实施节能项目",icon:TrendingDown,desc:"长期降低运营排放与费用",tone:"purple",price:480,reduction:3.6},{name:"优化能源调度",icon:SlidersHorizontal,desc:"低投资优化峰谷与设备策略",tone:"orange",price:12,reduction:2.1},{name:"调整内部碳预算",icon:Target,desc:"按楼宇与科室重设目标",tone:"red",price:0,reduction:0},
];

function ScenarioSimulator() {
  const [carbonPrice,setCarbonPrice]=useState(85);
  const [annual,setAnnual]=useState(26780);
  const [greenPower,setGreenPower]=useState(18);
  const [offset,setOffset]=useState(6);
  const [saving,setSaving]=useState(5);
  const [growth,setGrowth]=useState(4);
  const budget=24500;
  const adjusted=annual*(1+growth/100)*(1-saving/100);
  const greenReduction=adjusted*.62*greenPower/100;
  const offsetReduction=adjusted*offset/100;
  const net=Math.max(0,adjusted-greenReduction-offsetReduction);
  const gap=net-budget;
  const cost=Math.max(0,gap)*carbonPrice;
  const recommendation=gap<=0?"当前组合可满足年度预算，建议保留 3% 安全余量。":greenPower<25?"优先将绿电比例提高至 25%，再用 CCER 覆盖剩余缺口。":saving<8?"建议追加冷站与洁净空调节能项目，降低长期履约成本。":"采用绿电 + 节能项目 + 少量 CCER 的组合成本最低。";
  const sliders=[{label:"碳价",value:carbonPrice,min:30,max:200,unit:"元/tCO₂",set:setCarbonPrice},{label:"预计全年排放量",value:annual,min:18000,max:36000,unit:"tCO₂e",set:setAnnual},{label:"绿电采购比例",value:greenPower,min:0,max:60,unit:"%",set:setGreenPower},{label:"碳信用抵消比例",value:offset,min:0,max:30,unit:"%",set:setOffset},{label:"节能率",value:saving,min:0,max:20,unit:"%",set:setSaving},{label:"业务增长率",value:growth,min:-5,max:15,unit:"%",set:setGrowth}];
  const compareOption={tooltip:{trigger:"axis"},grid:{left:36,right:12,top:16,bottom:32},xAxis:{type:"category",data:["现状购买","绿电组合","节能组合","推荐组合"],...axisBase()},yAxis:{type:"value",...axisBase()},series:[{type:"bar",barWidth:24,data:[cost/10000,(cost*.82+greenPower*2.4),(cost*.65+saving*8),(cost*.54+greenPower*1.6+saving*5)].map((value,index)=>({value:Number(value.toFixed(1)),itemStyle:{color:["#ff6b6b","#22c8df","#9a76ff","#31d58b"][index],borderRadius:[5,5,0,0]}}))}]};
  return <Panel className="simulator-panel" title="情景模拟器" subtitle="拖动参数，实时测算预算缺口与最优策略" action={<span className="live-tag"><i/>实时计算</span>}><div className="simulator-grid"><div className="slider-stack">{sliders.map((item)=><label key={item.label}><span><b>{item.label}</b><em>{item.value.toLocaleString()} {item.unit}</em></span><input type="range" min={item.min} max={item.max} value={item.value} onChange={(e)=>item.set(Number(e.target.value))}/><small><i>{item.min}</i><i>{item.max}</i></small></label>)}</div><div className="sim-results"><div className="sim-kpis"><article className={gap>0?"danger":"success"}><span>预计预算缺口</span><b>{gap>0?"+":""}{Math.round(gap).toLocaleString()} <small>tCO₂e</small></b><em>{gap>0?"高风险":"预算内"}</em></article><article><span>预计资金缺口</span><b>¥{(cost/10000).toFixed(1)}<small>万</small></b><em>按当前碳价</em></article><article><span>可抵消排放量</span><b>{Math.round(greenReduction+offsetReduction).toLocaleString()} <small>tCO₂e</small></b><em>绿电 + 碳信用</em></article></div><Chart option={compareOption} height={210}/><div className="strategy-advice"><Leaf size={17}/><span><b>最优策略建议</b><small>{recommendation}</small></span></div></div></div></Panel>;
}

function TaskCenter() {
  const {tasks,updateTask,pushToast}=usePlatformStore();
  const [editing,setEditing]=useState<AnnualTask|null>(null);
  const [form,setForm]=useState<AnnualTask|null>(null);
  const open=(task:AnnualTask)=>{setEditing(task);setForm({...task});};
  const save=()=>{if(!form)return;updateTask(form);pushToast("任务已更新",`${form.title} 的负责人、进度和备注已保存。`,"success");setEditing(null);};
  return <Panel className="task-center" title="年度任务中心" subtitle={`${tasks.filter((task)=>task.status==="已完成").length}/${tasks.length} 已完成`} action={<Button><MoreHorizontal size={14}/></Button>}><div className="task-list">{tasks.map((task)=>{const days=dayjs(task.dueDate).diff(dayjs("2026-08-04"),"day");return <article key={task.id} className={task.status==="已逾期"?"overdue":""}><header><span className={`priority p-${task.priority}`}>{task.priority}</span><StatusBadge value={task.status}/></header><h3>{task.title}</h3><p>截止 {task.dueDate} · <em>{days<0?`已逾期 ${Math.abs(days)} 天`:`剩余 ${days} 天`}</em></p><small>负责人：{task.owner}</small><ProgressBar value={task.progress} tone={task.status==="已逾期"?"red":"green"}/><footer><b>{task.progress}%</b><div><button onClick={()=>{updateTask({...task,status:"已完成",progress:100});pushToast("任务已完成",task.title,"success");}}><Check size={13}/>完成</button><button onClick={()=>open(task)}><FilePenLine size={13}/>编辑</button></div></footer></article>})}</div><Modal open={Boolean(editing&&form)} onClose={()=>setEditing(null)} title="编辑年度任务" footer={<><Button onClick={()=>setEditing(null)}>取消</Button><Button variant="primary" onClick={save}>保存任务</Button></>}>{form&&<div className="form-grid"><FormField label="任务名称" required><input value={form.title} onChange={(e)=>setForm({...form,title:e.target.value})}/></FormField><FormField label="负责人" required><input value={form.owner} onChange={(e)=>setForm({...form,owner:e.target.value})}/></FormField><FormField label="截止日期" required><input type="date" value={form.dueDate} onChange={(e)=>setForm({...form,dueDate:e.target.value})}/></FormField><FormField label="当前进度"><input type="number" min="0" max="100" value={form.progress} onChange={(e)=>setForm({...form,progress:Number(e.target.value)})}/></FormField><FormField label="任务状态"><select value={form.status} onChange={(e)=>setForm({...form,status:e.target.value as AnnualTask["status"]})}><option>待开始</option><option>进行中</option><option>已完成</option><option>已逾期</option></select></FormField><FormField label="优先级"><select value={form.priority} onChange={(e)=>setForm({...form,priority:e.target.value as AnnualTask["priority"]})}><option>高</option><option>中</option><option>低</option></select></FormField><FormField label="任务备注"><textarea rows={4} value={form.note} onChange={(e)=>setForm({...form,note:e.target.value})}/></FormField></div>}</Modal></Panel>;
}

function StrategyCards() {
  const {addStrategy,addTask,addTransaction,pushToast}=usePlatformStore();
  const [selected,setSelected]=useState<typeof strategies[number]|null>(null);
  const [form,setForm]=useState({quantity:1000,unitPrice:85,reduction:1000,cycle:"3个月",funding:"年度节能专项",department:"后勤保障部"});
  const submit=()=>{if(!selected)return;if(form.quantity<=0||form.unitPrice<0||form.reduction<0){pushToast("参数不合法","数量、单价和预计减排量必须为有效数值。","warning");return;}const plan:StrategyPlan={id:crypto.randomUUID(),title:selected.name,...form,createdAt:new Date().toISOString()};addStrategy(plan);addTask({id:crypto.randomUUID(),title:selected.name,dueDate:dayjs().add(90,"day").format("YYYY-MM-DD"),owner:form.department,progress:0,status:"待开始",note:`资金来源：${form.funding}；预计减排 ${form.reduction} tCO₂e`,priority:"中"});if(selected.name.includes("购买"))addTransaction({id:crypto.randomUUID(),assetType:selected.name.includes("CCER")?"CCER":selected.name.includes("绿证")?"绿证":selected.name.includes("绿电")?"绿电":"碳信用",direction:"买入",quantity:form.quantity,unitPrice:form.unitPrice,amount:form.quantity*form.unitPrice,date:dayjs().format("YYYY-MM-DD"),counterparty:"待确定供应商",contractNo:`PLAN-${Date.now()}`,operator:"当前用户",reviewStatus:"待审核"});pushToast("已加入年度方案",`${selected.name} 已同步到任务计划${selected.name.includes("购买")?"和资产台账":""}。`,"success");setSelected(null);};
  return <Panel title="履约或目标达成策略" subtitle="点击策略卡片，填写参数后加入年度方案"><div className="strategy-cards">{strategies.map((item)=>{const Icon=item.icon;return <button key={item.name} className={`tone-${item.tone}`} onClick={()=>{setSelected(item);setForm((s)=>({...s,unitPrice:item.price,reduction:item.reduction*1000}));}}><span><Icon size={20}/></span><b>{item.name}</b><small>{item.desc}</small><em>开始测算 <ChevronRight size={13}/></em></button>})}</div><Modal open={Boolean(selected)} onClose={()=>setSelected(null)} title={`${selected?.name??"策略"}测算`} subtitle="提交后将同步更新年度任务计划与资产台账" footer={<><Button onClick={()=>setSelected(null)}>取消</Button><Button variant="primary" onClick={submit}>加入方案</Button></>}><div className="form-grid"><FormField label="数量" required><input type="number" min="1" value={form.quantity} onChange={(e)=>setForm({...form,quantity:Number(e.target.value)})}/></FormField><FormField label="单价（元）" required><input type="number" min="0" step="0.01" value={form.unitPrice} onChange={(e)=>setForm({...form,unitPrice:Number(e.target.value)})}/></FormField><FormField label="预计减排量（tCO₂e）" required><input type="number" min="0" value={form.reduction} onChange={(e)=>setForm({...form,reduction:Number(e.target.value)})}/></FormField><FormField label="实施周期"><input value={form.cycle} onChange={(e)=>setForm({...form,cycle:e.target.value})}/></FormField><FormField label="资金来源"><select value={form.funding} onChange={(e)=>setForm({...form,funding:e.target.value})}><option>年度节能专项</option><option>医院自有资金</option><option>合同能源管理</option><option>科研项目资金</option></select></FormField><FormField label="责任部门"><select value={form.department} onChange={(e)=>setForm({...form,department:e.target.value})}><option>后勤保障部</option><option>财务资产部</option><option>采购中心</option><option>设备动力科</option></select></FormField></div><div className="estimate-summary"><span>预计总投入<b>¥{(form.quantity*form.unitPrice/10000).toFixed(1)} 万</b></span><span>预计减排<b>{form.reduction.toLocaleString()} tCO₂e</b></span></div></Modal></Panel>;
}

function TransactionLedger() {
  const {transactions,addTransaction,updateTransaction,voidTransaction,role,pushToast}=usePlatformStore();
  const [editing,setEditing]=useState<AssetTransaction|null|"new">(null);
  const blank:AssetTransaction={id:crypto.randomUUID(),assetType:"绿证",direction:"买入",quantity:100,unitPrice:46,amount:4600,date:dayjs().format("YYYY-MM-DD"),counterparty:"",contractNo:"",operator:"当前用户",reviewStatus:"待审核"};
  const [form,setForm]=useState<AssetTransaction>(blank);
  const [errors,setErrors]=useState<Record<string,string>>({});
  const canEdit=role==="管理员"||role==="核算员";
  const open=(transaction?:AssetTransaction)=>{setEditing(transaction??"new");setForm(transaction?{...transaction}:{...blank,id:crypto.randomUUID()});setErrors({});};
  const save=()=>{const e:Record<string,string>={};if(!form.counterparty.trim())e.counterparty="请输入交易对手";if(!form.contractNo.trim())e.contractNo="请输入合同编号";if(form.quantity<=0)e.quantity="数量必须大于 0";setErrors(e);if(Object.keys(e).length)return;const next={...form,amount:form.quantity*form.unitPrice};if(editing==="new")addTransaction(next);else updateTransaction(next);pushToast("交易已保存",`${next.assetType} ${next.direction} ${next.quantity}，资产余额已刷新。`,"success");setEditing(null);};
  const columns:ColumnDef<AssetTransaction>[]=[
    {accessorKey:"date",header:"交易日期"},{accessorKey:"assetType",header:"资产类型",cell:({row})=><StatusBadge value={row.original.assetType}/>},{accessorKey:"direction",header:"方向"},{accessorKey:"quantity",header:"数量",cell:({row})=>row.original.quantity.toLocaleString()},{accessorKey:"unitPrice",header:"单价",cell:({row})=>`¥${row.original.unitPrice}`},{accessorKey:"amount",header:"总金额",cell:({row})=><b>¥{row.original.amount.toLocaleString()}</b>},{accessorKey:"counterparty",header:"交易对手"},{accessorKey:"contractNo",header:"合同编号"},{accessorKey:"operator",header:"经办人"},{accessorKey:"reviewStatus",header:"审核状态",cell:({row})=><StatusBadge value={row.original.reviewStatus}/>},{id:"actions",header:"操作",cell:({row})=><div className="row-actions"><button disabled={!canEdit||row.original.reviewStatus==="已撤销"} onClick={()=>open(row.original)}><Pencil size={14}/></button><button className="danger" disabled={!canEdit||row.original.reviewStatus==="已撤销"} onClick={()=>{if(confirm(`确定撤销交易 ${row.original.contractNo}？`)){voidTransaction(row.original.id);pushToast("交易已撤销","资产余额已按撤销后的台账重新计算。","warning");}}}><Trash2 size={14}/></button></div>}
  ];
  return <><DataTable data={transactions} columns={columns} title="碳资产交易记录" subtitle="新增、编辑或撤销交易后，资产余额和资产价值实时刷新" actions={<><Button disabled={!canEdit} onClick={()=>open()}><Plus size={14}/>新增交易</Button><Button onClick={()=>downloadWorkbook({交易记录:transactions as unknown as Record<string,unknown>[]},"医院碳资产交易记录.xlsx")}><Download size={14}/>导出</Button></>}/><Modal open={Boolean(editing)} onClose={()=>setEditing(null)} title={editing==="new"?"新增碳资产交易":"编辑碳资产交易"} footer={<><Button onClick={()=>setEditing(null)}>取消</Button><Button variant="primary" onClick={save}>保存交易</Button></>}><div className="form-grid"><FormField label="资产类型" required><select value={form.assetType} onChange={(e)=>setForm({...form,assetType:e.target.value as AssetTransaction["assetType"]})}><option>碳信用</option><option>CCER</option><option>绿证</option><option>绿电</option><option>内部碳配额</option></select></FormField><FormField label="买入／卖出" required><select value={form.direction} onChange={(e)=>setForm({...form,direction:e.target.value as AssetTransaction["direction"]})}><option>买入</option><option>卖出</option></select></FormField><FormField label="数量" required error={errors.quantity}><input type="number" min="1" value={form.quantity} onChange={(e)=>setForm({...form,quantity:Number(e.target.value)})}/></FormField><FormField label="单价（元）" required><input type="number" min="0" step=".01" value={form.unitPrice} onChange={(e)=>setForm({...form,unitPrice:Number(e.target.value)})}/></FormField><FormField label="总金额"><input readOnly value={`¥${(form.quantity*form.unitPrice).toLocaleString()}`}/></FormField><FormField label="交易日期" required><input type="date" value={form.date} onChange={(e)=>setForm({...form,date:e.target.value})}/></FormField><FormField label="交易对手" required error={errors.counterparty}><input value={form.counterparty} onChange={(e)=>setForm({...form,counterparty:e.target.value})}/></FormField><FormField label="合同编号" required error={errors.contractNo}><input value={form.contractNo} onChange={(e)=>setForm({...form,contractNo:e.target.value})}/></FormField><FormField label="凭证附件"><input type="file" onChange={(e)=>setForm({...form,attachment:e.target.files?.[0]?.name})}/></FormField><FormField label="审核状态"><select value={form.reviewStatus} onChange={(e)=>setForm({...form,reviewStatus:e.target.value as AssetTransaction["reviewStatus"]})}><option>待审核</option><option>已通过</option></select></FormField></div></Modal></>;
}

function AssetTabContent({ tab }: { tab:AssetTab }) {
  const {transactions,tasks,strategies}=usePlatformStore();
  if(tab==="交易记录")return <TransactionLedger/>;
  if(tab==="月度排放与预算"){const option={tooltip:{trigger:"axis"},legend:{data:["预算","实际排放"],textStyle:{color:"#9fb0c9"}},grid:{left:42,right:20,top:42,bottom:30},xAxis:{type:"category",data:monthlyEmission.map((d)=>d.month),...axisBase()},yAxis:{type:"value",...axisBase()},series:[{name:"预算",type:"bar",barWidth:15,data:monthlyEmission.map((d)=>d.budget),itemStyle:{color:"#2f86ff",borderRadius:[4,4,0,0]}},{name:"实际排放",type:"bar",barWidth:15,data:monthlyEmission.map((d)=>d.actual||null),itemStyle:{color:"#6b778d",borderRadius:[4,4,0,0]}}]};return <Panel title="月度排放 vs 碳预算" subtitle="tCO₂e · 预算执行率 62.8%"><Chart option={option} height={310}/><div className="chart-summary"><span>年度总预算<b>24,500 tCO₂e</b></span><span>已核算排放<b>14,308 tCO₂e</b></span><span>年度预测差值<b className="danger-text">+1,280 tCO₂e</b></span></div></Panel>}
  if(tab==="合规雷达"){const option={radar:{indicator:[{name:"预算达成",max:100},{name:"资产充足",max:100},{name:"凭证完整",max:100},{name:"任务及时",max:100},{name:"核查准备",max:100},{name:"风险控制",max:100}],splitArea:{areaStyle:{color:["rgba(47,134,255,.02)","rgba(47,134,255,.07)"]}},axisName:{color:"#9fb0c9"}},series:[{type:"radar",data:[{value:[72,84,88,65,78,70],name:"当前合规能力",areaStyle:{opacity:.2}}]}]};return <Panel title="年度合规能力雷达" subtitle="预算、资产、凭证、任务和核查准备综合评价"><Chart option={option} height={330}/></Panel>}
  const mappings:Record<Exclude<AssetTab,"月度排放与预算"|"交易记录"|"合规雷达">,{title:string;items:{name:string;value:string;status:string}[]}>= {"碳资产增值":{title:"碳资产价值与增值机会",items:[{name:"绿证持仓价值",value:`¥${transactions.filter((t)=>t.assetType==="绿证"&&t.reviewStatus!=="已撤销").reduce((s,t)=>s+t.amount,0).toLocaleString()}`,status:"稳定"},{name:"CCER 市值变化",value:"+8.6%",status:"增值"},{name:"节能项目潜在收益",value:`${strategies.length*18.6+86.4} 万元`,status:"待核证"}]},"核查准备":{title:"年度核查准备清单",items:tasks.slice(0,4).map((t)=>({name:t.title,value:`${t.progress}%`,status:t.status}))},"减排项目":{title:"节能减排项目组合",items:[{name:"冷站群控优化",value:"预计减排 486 t",status:"验收中"},{name:"洁净空调排程联动",value:"预计减排 328 t",status:"实施中"},{name:"光伏二期",value:"预计减排 612 t",status:"审批中"},...strategies.map((s)=>({name:s.title,value:`预计减排 ${s.reduction} t`,status:"已纳入"}))]}};
  const current=mappings[tab as keyof typeof mappings];return <Panel title={current.title}><div className="asset-detail-list">{current.items.map((item)=><article key={item.name}><span><b>{item.name}</b><small>年度计划与资产台账联动</small></span><strong>{item.value}</strong><StatusBadge value={item.status}/><ChevronRight size={14}/></article>)}</div></Panel>;
}

export function CarbonAssetsPage() {
  const store=usePlatformStore();
  const [tab,setTab]=useState<AssetTab>("月度排放与预算");
  const budget=24500;
  const used=store.calculation.total;
  const balance=Math.max(0,budget-used);
  const holdings=store.transactions.filter((t)=>t.reviewStatus!=="已撤销").reduce((sum,tx)=>sum+(tx.direction==="买入"?tx.quantity:-tx.quantity),0);
  const assetValue=store.transactions.filter((t)=>t.reviewStatus!=="已撤销").reduce((sum,tx)=>sum+(tx.direction==="买入"?tx.amount:-tx.amount),0);
  const sourceOption={tooltip:{trigger:"item"},legend:{bottom:0,textStyle:{color:"#9fb0c9"}},series:[{type:"pie",radius:["48%","72%"],center:["50%","44%"],label:{show:false},data:[{name:"绿证",value:1200},{name:"CCER",value:850},{name:"碳信用",value:420},{name:"节能项目",value:680}]}]};
  return <PageState><div className="assets-page page-stack">
    <section className="asset-toolbar"><div><StatusBadge value={store.filters.mode}/><span>{store.filters.year}年度 · {store.filters.hospital}</span></div><div><Button onClick={()=>downloadWorkbook({交易记录:store.transactions as unknown as Record<string,unknown>[],年度任务:store.tasks as unknown as Record<string,unknown>[]},"医院碳资产台账.xlsx")}><Download size={14}/>导出</Button><Button onClick={()=>store.pushToast("页面设置","图表口径与任务提醒设置已使用本地偏好保存。","info")}><Settings2 size={14}/>页面设置</Button></div></section>
    <section className="asset-top-grid"><div className="asset-overview"><Panel title={`年度碳资产总览 · ${store.filters.year}`} subtitle="兼容碳预算、内部配额、碳信用、CCER、绿证和节能项目"><div className="asset-balance"><article><span>年度碳预算</span><b>{budget.toLocaleString()} <small>tCO₂e</small></b></article><article><span>已使用</span><b>{used.toLocaleString()} <small>tCO₂e</small></b></article><article><span>剩余额度</span><b>{balance.toLocaleString()} <small>tCO₂e</small></b></article><article className="danger"><span>预计年度缺口</span><b>1,280 <small>tCO₂e</small></b></article></div><div className="asset-mini-grid"><div><h3>资产来源构成</h3><Chart option={sourceOption} height={210}/></div><div className="asset-stats"><span>绿证数量<b>{store.transactions.filter((t)=>t.assetType==="绿证"&&t.reviewStatus!=="已撤销").reduce((s,t)=>s+(t.direction==="买入"?t.quantity:-t.quantity),0).toLocaleString()} 张</b></span><span>碳信用数量<b>{holdings.toLocaleString()} tCO₂e</b></span><span>资产账面价值<b>¥{(assetValue/10000).toFixed(1)} 万</b></span><span>项目预计减排<b>{(1860+store.strategies.reduce((s,p)=>s+p.reduction,0)).toLocaleString()} t</b></span></div></div></Panel></div><ScenarioSimulator/><TaskCenter/></section>
    <StrategyCards/>
    <section className="asset-bottom"><div className="asset-tabs"><Segmented value={tab} options={["月度排放与预算","交易记录","碳资产增值","合规雷达","核查准备","减排项目"]} onChange={setTab}/></div><AssetTabContent tab={tab}/></section>
  </div></PageState>;
}
